AI_TELLS = sorted(list(set([
    "as an ai language model, i…", "as requested, here is…",
    "certainly! here’s a…", "i hope this helps.",
    "please let me know if you need anything else.",
    "if you have any other questions, feel free to ask.",
    "i’m happy to assist you with…", "based on your input, here is…",
    "to answer your question, …", "it’s important to note that…",
    "in conclusion,", "in summary,", "here’s a breakdown…",
    "here are some suggestions…", "this can be achieved by…",
    "as shown above/below,", "let’s explore this further…",
    "here is an example:", "here are a few key points to consider:",
    "please note:", "you may also want to consider…",
    "if you’d like more information, let me know.", "the following are…",
    "it’s worth mentioning that…", "keep in mind that…",
    "for your convenience, here’s…", "in this response, i will…",
    "it is important to understand that…", "let’s take a closer look at…",
    "with that said,", "to provide more detail,", "to summarize,",
    "here’s what you need to know:", "that being said,",
    "to elaborate further,", "below is…", "let’s break it down:",
    "for example,", "to get started,", "as a helpful assistant,",
    "i can provide you with…", "in other words,", "this is because…",
    "here’s how you can…", "this process involves…",
    "by following these steps,", "let’s dive in,",
    "let me know if you need additional clarification.", "leverage",
    "streamline", "optimize", "synergy", "robust", "scalable", "end-to-end",
    "seamless", "state-of-the-art", "cutting-edge", "transformative",
    "solution-oriented", "holistic approach", "user-centric",
    "paradigm shift", "game-changer", "ecosystem", "workflow", "automate",
    "orchestrate", "innovate", "best practices", "actionable insights",
    "data-driven", "ai-powered", "next-generation", "real-time",
    "drive value", "unlock potential", "empower", "iterate", "alignment",
    "unlock new possibilities", "enhanced", "dynamic", "integrate", "modular",
    "turnkey solution", "frictionless", "intelligent", "scalability",
    "disruptive", "mission-critical", "personalized experience",
    "granular control", "cross-functional", "kpi-driven", "context-aware",
    "industry-leading", "benchmark", "framework", "deployment", "api-first",
    "plug-and-play", "hyperautomation", "digital transformation",
    "overuse of em dashes (“—”)", "excessively correct oxford commas",
    "double spaces after periods", "overly neat bulleted/numbered lists",
    "markdown formatting", "quoting or italicizing inline",
    "as mentioned earlier,", "as previously discussed,",
    "according to your request,", "let’s proceed as follows,", "i will now…",
    "let’s address your question in detail:", "now, let’s move on to…",
    "as outlined above,", "below are…", "the steps are as follows:",
    "please note that i am an ai developed by",
    "always consult a qualified professional",
    "this information is for educational purposes only",
    "i am not a lawyer, but…", "i am not a medical professional, so…",
    "make sure to double-check…", "remember, this is just an example…",
    "step 1, step 2, step 3", "unusually balanced sections/paragraphs",
    "segue phrases at the start/end of each section", "additionally,",
    "moreover,", "furthermore,", "consequently,", "in contrast,", "however,",
    "overly formal tone", "over-explaining simple things", "significantly",
    "effectively", "efficiently", "particularly", "primarily", "essentially",
    "subsequently", "comprehensive", "holistic", "detailed", "thorough",
    "exhaustive", "pivotal", "critical", "integral", "seamlessly",
    "robustly", "intuitively", "dynamically", "proactively",
    "i hope this provides clarity.",
    "let me know if you have any further questions.",
    "please let me know if you need more information.",
    "thank you for your question!",
    "if you need anything else, feel free to ask.",
    "looking forward to assisting you further.",
    "wishing you the best with your project.", "rare use of contractions",
    "direct restatement of user’s question", "overuse of passive voice",
    "uniform sentence length",
    "in-code comments that read like documentation",
    "use of the phrase “for example,” with a colon", "foundation model",
    "multimodal", "token efficiency/token window",
    "retrieval-augmented generation (rag)", "prompt engineering",
    "few-shot/zero-shot learning", "model alignment", "guardrails",
    "hallucination/hallucinate", "system prompt/user prompt",
    "chain-of-thought (cot)", "instruction tuning", "context window",
    "fine-tuning/fine-tuned", "temperature/top-k/top-p sampling",
    "model weights", "open weights/closed weights",
    "model quantization/lora adapters", "inference latency",
    "output token limit", "llmops", "prompt injection/prompt leakage",
    "red-teaming", "synthetic data", "safety review",
    "fact-checking pipeline", "output filtering", "safety system",
    "explainability/interpretable ai", "self-consistency", "token gating",
    "voice cloning", "responsible ai", "model distillation",
    "here��s a quick summary:", "you can find more details at [link]",
    "let me walk you through…", "here’s what i found for you:",
    "certainly, here’s a list:", "if you’d like to continue, just ask!",
    "let’s break this down:", "here are some steps you can follow:",
    "if you’d like me to elaborate…", "(just to clarify)", "deep dive",
    "delve", "unpack", "let’s explore",
    "remember that ai models are not perfect…", "this function does x",
    "perfectly formatted code blocks",
    "excessively complete error-handling in examples",
    'print("hello, world!")', "explaining every variable and parameter",
    "for example, a restaurant may want to…",
    "imagine you’re building an app that…",
    "suppose you have a dataset with…", "teaching a student",
    "training a dog", "learning a language",
    "here are some next steps you can take:",
    "consider the following options:",
    "to further enhance your workflow, you might want to…",
])))