AI_TELL_SUGGESTIONS = {
    "as an ai language model, i…": ['I am a large language model, and', 'As a large language model,', 'As a language model,'],
    "as requested, here is…": ['Here is what you asked for:', 'Here is', 'Here is the information you requested:'],
    "certainly! here’s a…": ['Of course, here is', 'Certainly, here is', 'Here is'],
    "i hope this helps.": ['I hope this is useful.', 'I hope this is helpful.', 'I hope this answers your question.'],
    "please let me know if you need anything else.": ["I'm here if you need anything else.", 'Feel free to ask if you need anything else.', 'Let me know if you need anything else.'],
    "if you have any other questions, feel free to ask.": ['Feel free to ask any other questions.', 'Let me know if you have any other questions.', "I'm here if you have any other questions."],
    "i’m happy to assist you with…": ['I can help you with', 'I can assist you with', 'I can help with'],
    "based on your input, here is…": ['Here is a response to your input:', 'Based on your input,', 'Here is what I found based on your input:'],
    "to answer your question, …": ['In response to your question,', 'To answer you,', 'The answer is'],
    "it’s important to note that…": ['Note that', 'Remember that', 'Keep in mind'],
    "in conclusion,": ['To conclude,', 'In summary,', 'To sum up,'],
    "in summary,": ['To summarize,', 'In short,', 'Briefly,'],
    "here’s a breakdown…": ['The steps are:', 'Here is the process:', 'Here is a breakdown:'],
    "here are some suggestions…": ['Here are some thoughts:', 'Here are some recommendations:', 'Here are some ideas:'],
    "this can be achieved by…": ['This is possible by', 'This can be done by', 'You can do this by'],
    "as shown above/below,": ['As you can see,', 'As shown above,', 'As shown below,'],
    "let’s explore this further…": ["Let's explore this more,", "Let's look at this further,", "Let's examine this further,"],
    "here is an example:": ['As an example:', 'For example:', 'For instance:'],
    "here are a few key points to consider:": ['Keep these points in mind:', 'Here are some important points:', 'Consider these points:'],
    "please note:": ['Remember:', 'Keep in mind:', 'Note:'],
    "you may also want to consider…": ['You could also consider', 'Another option is', 'You might also consider'],
    "if you’d like more information, let me know.": ['Let me know if you want more information.', "I'm here if you want more information.", "I can provide more information if you'd like."],
    "the following are…": ['The following is', 'Here are', 'Below are'],
    "it’s worth mentioning that…": ['Note that', "It's important to note that", "It's worth noting that"],
    "keep in mind that…": ['Note that', "It's important to remember that", 'Remember that'],
    "for your convenience, here’s…": ['For your convenience,', 'Here is', 'Here are'],
    "in this response, i will…": ['I will', "I'll", 'In this response,'],
    "it is important to understand that…": ["It's important to understand that", 'You should know that', "It's important to know that"],
    "let’s take a closer look at…": ["Let's examine", "Let's analyze", "Let's investigate"],
    "with that said,": ['However,', 'Nonetheless,', 'Nevertheless,'],
    "to provide more detail,": ['To provide more details,', 'To be more specific,', 'In more detail,'],
    "to summarize,": ['To sum up,', 'In short,', 'Briefly,'],
    "here’s what you need to know:": ['This is what you need to know:', 'Here are the key points:', 'Here is what you need to know:'],
    "that being said,": ['However,', 'Nonetheless,', 'Nevertheless,'],
    "to elaborate further,": ['To elaborate,', 'To explain further,', 'In more detail,'],
    "below is…": ['The following is', 'Below are', 'Here is'],
    "let’s break it down:": ['The steps are:', 'Here is the process:', 'Here is a breakdown:'],
    "for example,": ['As an example,', 'For instance,', 'To illustrate,'],
    "to get started,": ['To begin,', 'To start,', 'First,'],
    "as a helpful assistant,": ['As an assistant,', 'As a resource,', 'As a tool,'],
    "i can provide you with…": ['I can provide you with', 'I can give you', 'I can offer you'],
    "in other words,": ['That is to say,', 'In simpler terms,', 'To put it another way,'],
    "this is because…": ['This is due to', 'This is a result of', 'The reason is'],
    "here’s how you can…": ['You can do this by', 'This is how to', "Here's how to"],
    "this process involves…": ['The process is', 'This involves', 'The steps are'],
    "by following these steps,": ['Follow these steps:', 'By doing this,', 'This will'],
    "let’s dive in,": ["Let's begin,", "Let's get started,", "Let's start,"],
    "let me know if you need additional clarification.": ['Feel free to ask for more clarification.', 'Let me know if you need more clarification.', "I'm here if you need more clarification."],
    "(just to clarify)": ['Just to be clear,', 'To be clear,', 'For clarity,'],
    "according to your request,": ['Here is the information you requested:', 'Here is what you asked for:', 'As you requested,'],
    "actionable insights": ['concrete suggestions', 'useful information', 'practical advice'],
    "additionally,": ['In addition,', 'Furthermore,', 'Also,'],
    "ai-powered": ['AI-assisted', 'using AI', 'with AI'],
    "alignment": ['conjunction', 'harmony', 'alinement', 'coalition', 'alliance', 'agreement', 'alignment', 'coordination'],
    "always consult a qualified professional": ['consult a professional', 'seek expert advice', 'talk to an expert'],
    "api-first": ['integration-ready', 'developer-focused', 'platform-based'],
    "as mentioned earlier,": ['As previously stated,', 'As mentioned,', 'As I said before,'],
    "as outlined above,": ['As described above,', 'As shown above,', 'As detailed earlier,'],
    "as previously discussed,": ['As mentioned before,', 'As we covered,', 'As we discussed,'],
    "automate": ['simplify', 'streamline', 'automate', 'automatise', 'computerize', 'automatize'],
    "below are…": ['The following is', 'Below is', 'Here are'],
    "benchmark": ['guideline', 'standard', 'bench mark', 'benchmark', 'point of reference'],
    "best practices": ['standard procedures', 'effective techniques', 'proven methods'],
    "certainly, here’s a list:": ['Certainly, here is a list:', 'Of course, here is a list:', 'Here is a list:'],
    "chain-of-thought (cot)": ['thought process', 'logical steps', 'reasoning process'],
    "comprehensive": ['all-inclusive', 'thorough', 'comp', 'comprehensive', 'comprehensive examination', 'complete'],
    "consequently,": ['Therefore,', 'Accordingly,', 'As a result,'],
    "consider the following options:": ['You could consider:', 'You might want to consider:', 'Here are some options:'],
    "context window": ['text capacity', 'input limit', 'prompt size'],
    "context-aware": ['intuitive', 'responsive', 'adaptive'],
    "critical": ['critical', 'vital', 'essential', 'crucial', 'decisive'],
    "cross-functional": ['interdisciplinary', 'team-based', 'collaborative'],
    "cutting-edge": ['innovative', 'with-it', 'up-to-date', 'cutting-edge', 'advanced', 'leading'],
    "data-driven": ['analytical', 'evidence-based', 'fact-based'],
    "deep dive": ['detailed look', 'in-depth analysis', 'thorough examination'],
    "delve": ['explore', 'investigate', 'dig', 'delve', 'examine', 'turn over', 'cut into'],
    "deployment": ['launch', 'implementation', 'deployment', 'rollout'],
    "detailed": ['elaborate', 'detail', 'detailed', 'thorough', 'comprehensive', 'in-depth', 'elaborated'],
    "digital transformation": ['tech upgrade', 'modernization', 'digitization'],
    "direct restatement of user’s question": ['rephrasing the question', "mirroring the user's words", 'repeating the question'],
    "disruptive": ['riotous', 'troubled', 'turbulent', 'disruptive', 'innovative', 'revolutionary', 'groundbreaking', 'tumultuous'],
    "double spaces after periods": ['standard spacing', 'single space after periods', 'correct spacing'],
    "drive value": ['add worth', 'create benefits', 'generate returns'],
    "dynamic": ['active', 'dynamic', 'moral force', 'energetic', 'dynamical', 'changing'],
    "dynamically": ['in real time', 'adaptively', 'on the fly', 'dynamically'],
    "ecosystem": ['community', 'ecosystem', 'network', 'environment'],
    "effectively": ['productively', 'successfully', 'efficaciously', 'effectively', 'in effect', 'efficiently'],
    "efficiently": ['productively', 'expeditiously', 'successfully', 'effectively', 'efficiently'],
    "empower": ['authorize', 'enable', 'invest', 'gift', 'indue', 'authorise', 'endue', 'support', 'empower', 'endow'],
    "end-to-end": ['comprehensive', 'end-to-end', 'full', 'throughout', 'complete'],
    "enhanced": ['enhanced', 'better', 'heighten', 'upgraded', 'raise', 'enhance', 'improved'],
    "essentially": ['fundamentally', 'essentially', 'in essence', 'basically'],
    "excessively complete error-handling in examples": ['simplified error handling', 'essential error handling', 'basic error checking'],
    "excessively correct oxford commas": ['standard comma style', 'consistent comma use', 'natural comma usage'],
    "exhaustive": ['exhaustive', 'thorough', 'in-depth', 'complete', 'thoroughgoing'],
    "explainability/interpretable ai": ['understandable AI', 'explainable AI', 'transparent AI'],
    "explaining every variable and parameter": ['focusing on important variables', 'explaining key parameters', 'summarizing variables'],
    "fact-checking pipeline": ['accuracy check', 'verification process', 'fact-checking system'],
    "few-shot/zero-shot learning": ['sample-efficient learning', 'learning from a few examples', 'few-example learning'],
    "fine-tuning/fine-tuned": ['refinement', 'adjustment', 'customization'],
    "for example, a restaurant may want to…": ['As an example,', 'For instance,', 'To illustrate,'],
    "foundation model": ['core model', 'base model', 'general-purpose model'],
    "framework": ['guideline', 'framework', 'model', 'system', 'fabric', 'structure', 'theoretical account'],
    "frictionless": ['smooth', 'easy', 'effortless', 'frictionless'],
    "furthermore,": ['In addition,', 'Also,', 'Moreover,'],
    "game-changer": ['breakthrough', 'milestone', 'innovation'],
    "granular control": ['fine-tuned adjustments', 'precise oversight', 'detailed management'],
    "guardrails": ['limitations', 'safety measures', 'constraints', 'safety rail', 'guardrail'],
    "hallucination/hallucinate": ['fabrication', 'making things up', 'inventing information'],
    "here are some next steps you can take:": ['Moving forward:', 'Next steps:', 'What to do next:'],
    "here are some steps you can follow:": ['Follow these steps:', 'Here are the steps:', "Here's how:"],
    "here’s what i found for you:": ['I found this for you:', 'Here is some information:', 'Here is what I found:'],
    "here��s a quick summary:": ['To summarize,', 'In short,', 'Briefly,'],
    "holistic": ['holistic', 'integrated', 'all-encompassing', 'comprehensive'],
    "holistic approach": ['all-encompassing strategy', 'integrated perspective', 'comprehensive view'],
    "however,": ['Nonetheless,', 'Nevertheless,', 'But,'],
    "hyperautomation": ['advanced automation', 'end-to-end automation', 'intelligent automation'],
    "i am not a lawyer, but…": ["I'm not qualified to give legal advice, but", 'This is not legal advice, but', "While I'm not a lawyer,"],
    "i am not a medical professional, so…": ['This is not medical advice, but', "While I'm not a medical professional,", "I'm not qualified to give medical advice, but"],
    "i hope this provides clarity.": ['I hope this is clear.', 'I hope this makes sense.', 'I hope this clarifies things.'],
    "i will now…": ['I will', "I'll", 'Next, I will'],
    "if you need anything else, feel free to ask.": ["I'm here if you need anything else.", 'Feel free to ask if you need anything else.', 'Let me know if you need anything else.'],
    "if you’d like me to elaborate…": ["I can explain further if you'd like.", 'Let me know if you want me to elaborate.', "If you'd like more detail,"],
    "if you’d like to continue, just ask!": ["I can continue if you'd like.", 'Just ask to continue.', 'Let me know if you want to continue.'],
    "imagine you’re building an app that…": ["Suppose you're developing an app that", 'For example, if you were building an app that', "Imagine you're creating an app that"],
    "in contrast,": ['On the other hand,', 'However,', 'Conversely,'],
    "in-code comments that read like documentation": ['brief code comments', 'concise comments', 'to-the-point comments'],
    "industry-leading": ['foremost', 'premier', 'top-tier'],
    "inference latency": ['response time', 'processing speed', 'prediction delay'],
    "innovate": ['create', 'innovate', 'introduce', 'pioneer', 'develop'],
    "instruction tuning": ['instruction-based learning', 'task-specific training', 'fine-tuning with instructions'],
    "integral": ['vital', 'constitutional', 'essential', 'entire', 'fundamental', 'built-in', 'inbuilt', 'inherent', 'intact', 'integral'],
    "integrate": ['merge', 'integrate', 'combine', 'unify', 'mix', 'desegregate', 'incorporate'],
    "intelligent": ['reasoning', 'sound', 'intelligent', 'smart', 'thinking', 'clever', 'level-headed', 'levelheaded', 'healthy', 'well-informed', 'advanced'],
    "intuitively": ['naturally', 'easily', 'intuitively', 'instinctively'],
    "iterate": ['iterate', 'restate', 'repeat', 'improve', 'retell', 'reiterate', 'refine', 'ingeminate', 'develop'],
    "kpi-driven": ['data-backed', 'performance-based', 'results-oriented'],
    "learning a language": ['mastering a language', 'studying a language', 'acquiring a language'],
    "let me know if you have any further questions.": ['Feel free to ask any other questions.', 'Let me know if you have any other questions.', "I'm here if you have any other questions."],
    "let me walk you through…": ['Let me guide you through', 'Let me show you', 'Let me explain'],
    "let’s address your question in detail:": ["Let's answer your question in detail:", "Let's discuss your question in detail:", "Let's go over your question in detail:"],
    "let’s break this down:": ['The steps are:', 'Here is the process:', 'Here is a breakdown:'],
    "let’s explore": ["Let's look at", "Let's examine", "Let's investigate"],
    "let’s proceed as follows,": ["Here's how we'll proceed:", "Here's the plan:", "Let's do this:"],
    "leverage": ['purchase', 'leverage', 'leveraging', 'utilize', 'take advantage of', 'use'],
    "llmops": ['LLM deployment', 'large language model operations', 'managing LLMs'],
    "looking forward to assisting you further.": ["I'm happy to help further.", "I'm here to assist you further.", 'I look forward to helping you more.'],
    "make sure to double-check…": ['Be sure to verify', 'Double-check', 'Confirm'],
    "markdown formatting": ['text styling', 'rich text formatting', 'standard formatting'],
    "mission-critical": ['crucial', 'essential', 'vital'],
    "model alignment": ['AI safety', 'matching model behavior to human values', 'value alignment'],
    "model distillation": ['knowledge transfer', 'simplification', 'summarization'],
    "model quantization/lora adapters": ['model compression', 'reducing model size', 'model optimization'],
    "model weights": ['model data', 'model parameters', 'neural network weights'],
    "modular": ['modular', 'adaptable', 'flexible', 'customizable'],
    "moreover,": ['In addition,', 'Furthermore,', 'Also,'],
    "multimodal": ['mixed-media', 'text, image, and audio', 'multiple data types'],
    "next-generation": ['futuristic', 'advanced', 'new'],
    "now, let’s move on to…": ['Moving on to', "Now, let's talk about", 'Next,'],
    "open weights/closed weights": ['shared model', 'open-source model', 'publicly available model'],
    "optimize": ['improve', 'optimise', 'refine', 'enhance', 'optimize'],
    "orchestrate": ['direct', 'mastermind', 'manage', 'organise', 'organize', 'coordinate', 'engineer', 'orchestrate'],
    "output filtering": ['result filtering', 'content moderation', 'output control'],
    "output token limit": ['response length limit', 'token limit', 'output size constraint'],
    "over-explaining simple things": ['getting to the point', 'being concise', 'avoiding over-explanation'],
    "overly formal tone": ['a relaxed tone', 'a conversational style', 'a more natural tone'],
    "overly neat bulleted/numbered lists": ['basic lists', 'standard lists', 'simple lists'],
    "overuse of em dashes (“—”)": ['using other punctuation', 'varying punctuation', 'using commas or parentheses'],
    "overuse of passive voice": ['stronger verbs', 'using active voice', 'more direct language'],
    "paradigm shift": ['fundamental shift', 'new way of thinking', 'major change'],
    "particularly": ['specially', 'peculiarly', 'particularly', 'specifically', 'especially', 'in particular'],
    "perfectly formatted code blocks": ['readable code blocks', 'clear code examples', 'standard code formatting'],
    "personalized experience": ['individualized approach', 'tailored interaction', 'customized service'],
    "pivotal": ['critical', 'polar', 'vital', 'crucial', 'pivotal'],
    "please let me know if you need more information.": ['Let me know if you need more information.', "I'm here if you want more information.", "I can provide more information if you'd like."],
    "please note that i am an ai developed by": ['I am an AI developed by', 'I am a language model from', 'I am an AI from'],
    "plug-and-play": ['ready to go', 'simple to use', 'easy to install'],
    "primarily": ['principally', 'in the main', 'mostly', 'primarily', 'mainly', 'chiefly', 'in the first place'],
    'print("hello, world!")': ['starter code', 'basic code example', 'simple program'],
    "proactively": ['acting in advance', 'taking initiative', 'being prepared'],
    "prompt engineering": ['prompt design', 'AI whispering', 'writing effective prompts'],
    "prompt injection/prompt leakage": ['malicious prompt insertion', 'AI manipulation', 'prompt hacking'],
    "quoting or italicizing inline": ['consistent emphasis', 'natural emphasis', 'using standard emphasis'],
    "rare use of contractions": ['using contractions', 'a conversational style', 'a more natural tone'],
    "real-time": ['real-time', 'instantaneous', 'immediate', 'live'],
    "red-teaming": ['ethical hacking', 'adversarial testing', 'simulated attack'],
    "remember that ai models are not perfect…": ['AI models are not perfect.', 'AI can make mistakes.', 'AI is not always accurate.'],
    "remember, this is just an example…": ['This is just an example.', 'For example:', 'This is an illustration.'],
    "responsible ai": ['trustworthy AI', 'ethical AI', 'safe AI'],
    "retrieval-augmented generation (rag)": ['RAG', 'knowledge-based generation', 'retrieval-based generation'],
    "robust": ['reliable', 'robust', 'strong', 'rich', 'racy', 'durable', 'full-bodied'],
    "robustly": ['dependably', 'robustly', 'solidly', 'strongly'],
    "safety review": ['risk assessment', 'safety check', 'security audit'],
    "safety system": ['security system', 'safety feature', 'protection mechanism'],
    "scalability": ['expandability', 'flexibility', 'scalability', 'growth potential'],
    "scalable": ['scalable', 'expandable', 'adaptable', 'flexible'],
    "seamless": ['seamless', 'uninterrupted', 'unseamed', 'smooth', 'effortless', 'unlined'],
    "seamlessly": ['effortlessly', 'without interruption', 'smoothly'],
    "segue phrases at the start/end of each section": ['smooth segues', 'clear connections', 'natural transitions'],
    "self-consistency": ['reasoning check', 'logical coherence', 'internal consistency'],
    "significantly": ['substantially', 'importantly', 'considerably', 'markedly', 'significantly'],
    "solution-oriented": ['results-focused', 'problem-solving', 'practical'],
    "state-of-the-art": ['modern', 'cutting-edge', 'state-of-the-art', 'advanced'],
    "step 1, step 2, step 3": ['in sequence', 'step-by-step', 'first, second, third'],
    "streamline": ['improve', 'make more efficient', 'simplify', 'streamline'],
    "subsequently": ['subsequently', 'afterward', 'later', 'after', 'afterwards', 'then', 'later on'],
    "suppose you have a dataset with…": ["Suppose you're working with a dataset that", 'For example, if you have a dataset with', 'Imagine you have a dataset with'],
    "synergy": ['synergy', 'teamwork', 'combined effort', 'collaboration', 'synergism'],
    "synthetic data": ['artificial data', 'generated data', 'fake data'],
    "system prompt/user prompt": ['system message', 'starting prompt', 'initial instruction'],
    "teaching a student": ['educating a student', 'guiding a student', 'instructing a student'],
    "temperature/top-k/top-p sampling": ['AI response randomness', 'model creativity settings', 'sampling parameters'],
    "thank you for your question!": ['Thank you for your question.', 'Thanks for asking!', "That's a great question."],
    "the steps are as follows:": ['The steps are:', 'Follow these steps:', 'Here are the steps:'],
    "this function does x": ['This function is for X', 'This function performs X action', "This function's purpose is X"],
    "this information is for educational purposes only": ['This is for educational purposes only.', 'This information is for learning purposes.', 'This is for informational purposes only.'],
    "thorough": ['exhaustive', 'thorough', 'comprehensive', 'in-depth', 'complete', 'thoroughgoing'],
    "to further enhance your workflow, you might want to…": ['To enhance your workflow, consider', 'To make your process better, you might want to', 'To improve your workflow, you could'],
    "token efficiency/token window": ['reducing token count', 'optimizing token usage', 'efficient tokenization'],
    "token gating": ['access control', 'content restriction', 'gated content'],
    "training a dog": ['teaching a dog', 'dog training', 'canine education'],
    "transformative": ['life-changing', 'game-changing', 'revolutionary'],
    "turnkey solution": ['complete package', 'ready-to-use system', 'all-in-one solution'],
    "uniform sentence length": ['a mix of long and short sentences', 'varied sentence length', 'dynamic sentence structure'],
    "unlock new possibilities": ['discover new potential', 'create new opportunities', 'open up new avenues'],
    "unlock potential": ['discover opportunities', 'tap into strengths', 'realize possibilities'],
    "unpack": ['unpack', 'break down', 'take out', 'explain', 'analyze'],
    "unusually balanced sections/paragraphs": ['organic structure', 'varied paragraph length', 'natural paragraphing'],
    "use of the phrase “for example,” with a colon": ["using 'for example' naturally", 'varying introductory phrases', 'natural examples'],
    "user-centric": ['intuitive', 'easy-to-use', 'user-focused'],
    "voice cloning": ['voice duplication', 'speech synthesis', 'voice replication'],
    "wishing you the best with your project.": ['Good luck with your project.', 'Best of luck with your project.', 'I wish you success with your project.'],
    "workflow": ['workflow', 'work flow', 'procedure', 'system', 'process'],
    "you can find more details at [link]": ['You can learn more at [link]', 'For more information, see [link]', 'More details are at [link]'],
}
