from database import SessionLocal, FAQ

def populate_faq():
    db = SessionLocal()
    
    # Clear existing FAQs to avoid duplicates
    db.query(FAQ).delete()

    faqs = [
        FAQ(question="What is DashAway?", answer="DashAway is a web-based text cleaning tool that helps you identify and fix common writing issues, specifically em-dashes, cliches, jargon, and AI tells."),
        FAQ(question="How do I use DashAway?", answer="Simply paste your text into the left panel and click the 'Clean Text' button. DashAway will highlight potential issues in the right panel. You can then click on each highlight to see suggestions for improvement."),
        FAQ(question="What are 'AI tells'?", answer="AI tells are common words, phrases, and formatting patterns that are characteristic of text generated by artificial intelligence. Removing them can make your writing sound more natural and human."),
        FAQ(question="Is DashAway free to use?", answer="DashAway offers a free trial with a limited number of runs. To get unlimited access, you can upgrade to one of our paid plans."),
        FAQ(question="What payment methods do you accept?", answer="We accept all major credit cards through our secure payment processor, Paddle."),
        FAQ(question="Can I cancel my subscription at any time?", answer="Yes, you can cancel your subscription at any time from your account settings. Your subscription will remain active until the end of the current billing period."),
        FAQ(question="Do you offer refunds?", answer="We offer a 7-day money-back guarantee for first-time subscribers. Please see our Refund Policy for more details."),
        FAQ(question="Is my data secure?", answer="Yes, we take data security very seriously. We use industry-standard encryption and security measures to protect your information. We never store the text you analyze."),
        FAQ(question="Do you have a browser extension?", answer="A browser extension is on our roadmap, but it is not available at this time."),
        FAQ(question="How can I provide feedback?", answer="We'd love to hear from you! You can submit feedback, bug reports, or feature requests through the 'Feedback' link in the footer."),
    ]

    db.add_all(faqs)
    db.commit()
    db.close()

if __name__ == '__main__':
    populate_faq()