JARGON_SUGGESTIONS = {
    "leverage": ["use", "utilize", "take advantage of"],
    "streamline": ["simplify", "make more efficient", "improve"],
    "optimize": ["improve", "refine", "enhance"],
    "synergy": ["collaboration", "teamwork", "combined effort"],
    "robust": ["strong", "durable", "reliable"],
    "scalable": ["expandable", "flexible", "adaptable"],
    "end-to-end": ["complete", "comprehensive", "full"],
    "seamless": ["smooth", "effortless", "uninterrupted"],
    "state-of-the-art": ["modern", "advanced", "cutting-edge"],
    "cutting-edge": ["innovative", "advanced", "leading"],
    "transformative": ["life-changing", "revolutionary", "game-changing"],
    "solution-oriented": ["problem-solving", "practical", "results-focused"],
    "holistic approach": ["comprehensive view", "all-encompassing strategy", "integrated perspective"],
    "user-centric": ["user-focused", "intuitive", "easy-to-use"],
    "paradigm shift": ["major change", "fundamental shift", "new way of thinking"],
    "game-changer": ["breakthrough", "innovation", "milestone"],
    "ecosystem": ["network", "community", "environment"],
    "workflow": ["process", "procedure", "system"],
    "automate": ["simplify", "streamline", "computerize"],
    "orchestrate": ["coordinate", "manage", "organize"],
    "innovate": ["create", "pioneer", "develop"],
    "best practices": ["standard procedures", "proven methods", "effective techniques"],
    "actionable insights": ["useful information", "practical advice", "concrete suggestions"],
    "data-driven": ["evidence-based", "analytical", "fact-based"],
    "ai-powered": ["using AI", "with AI", "AI-assisted"],
    "next-generation": ["new", "advanced", "futuristic"],
    "real-time": ["live", "instantaneous", "immediate"],
    "drive value": ["create benefits", "add worth", "generate returns"],
    "unlock potential": ["realize possibilities", "discover opportunities", "tap into strengths"],
    "empower": ["enable", "authorize", "support"],
    "iterate": ["refine", "improve", "develop"],
    "alignment": ["agreement", "coordination", "harmony"],
    "unlock new possibilities": ["create new opportunities", "open up new avenues", "discover new potential"],
    "enhanced": ["improved", "better", "upgraded"],
    "dynamic": ["energetic", "active", "changing"],
    "integrate": ["combine", "merge", "unify"],
    "modular": ["flexible", "adaptable", "customizable"],
    "turnkey solution": ["complete package", "all-in-one solution", "ready-to-use system"],
    "frictionless": ["effortless", "smooth", "easy"],
    "intelligent": ["smart", "clever", "advanced"],
    "scalability": ["expandability", "flexibility", "growth potential"],
    "disruptive": ["innovative", "groundbreaking", "revolutionary"],
    "mission-critical": ["essential", "vital", "crucial"],
    "personalized experience": ["tailored interaction", "customized service", "individualized approach"],
    "granular control": ["detailed management", "fine-tuned adjustments", "precise oversight"],
    "cross-functional": ["collaborative", "interdisciplinary", "team-based"],
    "kpi-driven": ["results-oriented", "performance-based", "data-backed"],
    "context-aware": ["intuitive", "responsive", "adaptive"],
    "industry-leading": ["top-tier", "premier", "foremost"],
    "benchmark": ["standard", "guideline", "point of reference"],
    "framework": ["structure", "system", "guideline"],
    "deployment": ["rollout", "implementation", "launch"],
    "api-first": ["developer-focused", "integration-ready", "platform-based"],
    "plug-and-play": ["easy to install", "simple to use", "ready to go"],
    "hyperautomation": ["advanced automation", "intelligent automation", "end-to-end automation"],
    "digital transformation": ["modernization", "digitization", "tech upgrade"],
    "synergize": ["collaborate", "combine forces", "work together"],
    "end-to-end": ["complete", "full", "comprehensive"],
    "holistic": ["comprehensive", "complete", "integrated"],
    "comprehensive": ["complete", "thorough", "full"],
    "best practices": ["standard procedures", "proven methods", "effective techniques"],
    "results-driven": ["focused on outcomes", "goal-oriented", "performance-based"],
    "best-in-class": ["top-performing", "leading", "premier"],
    "orchestration": ["coordination", "management", "arrangement"],
    "automation": ["automatic operation", "mechanization", "computerization"],
    "efficiency gains": ["improved productivity", "better use of resources", "increased output"],
    "optimize processes": ["improve workflows", "streamline operations", "refine procedures"],
    "streamlined process": ["simplified workflow", "efficient procedure", "smooth operation"],
    "personalized experience": ["tailored interaction", "customized service", "individualized approach"],
    "personalization": ["customization", "tailoring", "individualization"],
    "seamless integration": ["smooth combination", "effortless connection", "flawless merger"],
    "blueprint": ["plan", "design", "model"],
    "roadmap": ["plan", "strategy", "guide"],
    "benchmarks": ["standards", "criteria", "measures"],
    "benchmarked": ["measured against", "compared to", "evaluated against"],
    "benchmarked against": ["compared with", "measured against", "evaluated against"],
    "key performance indicators": ["metrics", "success measures", "goals"],
    "mission-driven": ["purpose-focused", "goal-oriented", "value-based"],
    "benchmarking": ["comparing", "evaluating", "assessing"],
    "core competency": ["key strength", "main skill", "primary expertise"],
    "digital-first": ["online-focused", "tech-centric", "web-based"],
    "cloud-native": ["designed for the cloud", "cloud-based", "cloud-centric"],
    "foundation model": ["base model", "core model", "fundamental model"],
    "token efficiency": ["token usage", "token optimization", "token performance"],
    "prompt engineering": ["prompt design", "prompt optimization", "prompt creation"],
    "few-shot learning": ["learning with few examples", "sample-efficient learning", "data-efficient learning"],
    "zero-shot learning": ["learning with no examples", "unseen data learning", "zero-data learning"],
    "model alignment": ["model tuning", "model calibration", "model adjustment"],
    "guardrails": ["safety measures", "protections", "safeguards"],
    "hallucination": ["model fabrication", "generated error", "factual inaccuracy"],
    "retrieval-augmented generation": ["RAG", "retrieval-based generation", "knowledge-intensive generation"],
    "context window": ["input limit", "token limit", "input size"],
    "system prompt": ["initial instruction", "base prompt", "guiding prompt"],
    "instruction tuning": ["fine-tuning with instructions", "instruction-based training", "task-specific tuning"],
    "fine-tuning": ["model specialization", "transfer learning", "domain adaptation"],
    "self-consistency": ["consistent output", "reliable generation", "stable results"],
    "chain-of-thought": ["reasoning process", "step-by-step thinking", "logical progression"],
    "inference latency": ["response time", "processing speed", "generation delay"],
    "model weights": ["model parameters", "network weights", "learned values"],
    "open weights": ["publicly available weights", "open-source model weights", "shared parameters"],
    "closed weights": ["proprietary weights", "private model weights", "non-public parameters"],
    "quantization": ["model compression", "weight reduction", "size optimization"],
    "lora adapters": ["low-rank adaptation", "efficient fine-tuning", "parameter-efficient tuning"],
    "distillation": ["knowledge transfer", "model compression", "teacher-student learning"],
    "output token limit": ["generation limit", "response length", "max tokens"],
    "llmops": ["large language model operations", "LLM lifecycle management", "AI model management"],
    "prompt injection": ["malicious prompt insertion", "prompt hacking", "input manipulation"],
    "prompt leakage": ["sensitive data exposure", "information disclosure", "private data extraction"],
    "red-teaming": ["adversarial testing", "security assessment", "vulnerability analysis"],
    "synthetic data": ["generated data", "artificial data", "simulated data"],
    "safety review": ["security audit", "risk assessment", "vulnerability scan"],
    "fact-checking pipeline": ["verification process", "accuracy check", "information validation"],
    "output filtering": ["content moderation", "response filtering", "result cleaning"],
    "safety system": ["protection mechanism", "security layer", "risk mitigation system"],
    "explainability": ["interpretability", "transparency", "model understanding"],
    "interpretable ai": ["explainable AI", "transparent AI", "understandable AI"],
    "responsible ai": ["ethical AI", "trustworthy AI", "accountable AI"],
    "bias mitigation": ["fairness enhancement", "prejudice reduction", "stereotype removal"],
    "human-in-the-loop": ["human oversight", "manual review", "human-AI collaboration"],
    "continuous improvement": ["ongoing enhancement", "constant refinement", "iterative development"],
    "iteration": ["version", "cycle", "repetition"],
    "feedback loop": ["improvement cycle", "learning process", "evaluation system"],
    "scalable infrastructure": ["expandable system", "flexible architecture", "growth-ready platform"],
    "best-of-breed": ["top-tier", "leading", "premier"],
    "world-class": ["excellent", "outstanding", "superior"],
    "market-leading": ["dominant", "top", "number one"],
    "best-value": ["most cost-effective", "best bang for the buck", "optimal price-quality ratio"],
    "compliant": ["in accordance with", "following the rules", "meeting standards"],
    "compliance": ["adherence to rules", "following regulations", "meeting standards"],
    "risk mitigation": ["risk reduction", "loss prevention", "damage control"],
    "market disruption": ["industry shake-up", "radical change", "paradigm shift"],
    "thought leadership": ["expert opinion", "industry influence", "visionary ideas"],
    "strategic partnership": ["alliance", "collaboration", "joint venture"],
    "collaborative approach": ["team-based method", "joint effort", "cooperative strategy"],
    "stakeholder engagement": ["involving interested parties", "communicating with stakeholders", "managing relationships"],
    "real-time analytics": ["live data analysis", "instant insights", "up-to-the-minute reporting"],
    "predictive analytics": ["forecasting", "future trend analysis", "data-based prediction"],
    "intelligent automation": ["smart automation", "AI-driven processes", "cognitive automation"],
    "smart solutions": ["intelligent systems", "advanced technology", "innovative answers"],
    "digital ecosystem": ["interconnected online services", "online platform", "digital environment"],
    "data pipeline": ["data workflow", "data processing system", "information flow"],
    "data lake": ["centralized data repository", "large-scale data storage", "raw data storage"],
    "data mesh": ["decentralized data architecture", "distributed data ownership", "domain-oriented data"],
    "cloud architecture": ["cloud infrastructure design", "cloud system layout", "cloud setup"],
    "cloud-enabled": ["cloud-compatible", "works with the cloud", "cloud-ready"],
    "hybrid cloud": ["mixed cloud environment", "public and private cloud", "combined cloud infrastructure"],
    "on-premise": ["in-house", "locally hosted", "self-hosted"],
    "agile methodology": ["iterative development", "flexible approach", "adaptive process"],
    "sprints": ["short development cycles", "focused work periods", "iterative work blocks"],
    "user journey": ["user experience map", "customer path", "interaction flow"],
    "customer journey": ["customer experience map", "user path", "interaction flow"],
    "customer-centric": ["customer-focused", "user-oriented", "client-first"],
    "customer-focused": ["customer-centric", "user-oriented", "client-first"],
    "elevate": ["raise", "improve", "enhance"],
    "transform": ["change", "revolutionize", "reshape"],
    "enable": ["allow", "permit", "facilitate"],
    "unlock value": ["create benefits", "realize potential", "generate returns"],
    "drive transformation": ["lead change", "spearhead innovation", "catalyze evolution"],
    "drive engagement": ["increase participation", "boost interaction", "foster involvement"],
    "continuous delivery": ["automated software release", "frequent deployments", "rapid delivery"],
    "continuous deployment": ["automated software release", "frequent deployments", "rapid delivery"],
    "end-user experience": ["user satisfaction", "customer happiness", "interaction quality"],
    "experience optimization": ["improving user satisfaction", "enhancing customer happiness", "refining interaction quality"],
    "business intelligence": ["data analysis for business", "insights from data", "data-driven decision making"],
    "insight-driven": ["data-informed", "evidence-based", "analytical"],
    "performance optimization": ["improving efficiency", "boosting speed", "enhancing output"],
    "visibility": ["transparency", "clarity", "openness"],
    "transparency": ["openness", "clarity", "honesty"],
    "seamless transition": ["smooth changeover", "easy migration", "effortless switch"],
    "transformation journey": ["process of change", "evolutionary path", "development story"],
    "change management": ["guiding organizational change", "managing transitions", "facilitating adaptation"],
    "stakeholder management": ["managing relationships with interested parties", "communicating with stakeholders", "handling expectations"],
    "process optimization": ["improving workflows", "streamlining operations", "refining procedures"],
    "digital maturity": ["level of digital adoption", "technological advancement", "digital readiness"],
    "maturity model": ["assessment framework", "development scale", "capability measurement"],
    "adoption curve": ["rate of acceptance", "diffusion of innovation", "user uptake"],
    "uplift": ["increase", "boost", "improvement"],
    "scalability assessment": ["evaluating growth potential", "testing expandability", "analyzing flexibility"],
    "resource allocation": ["distributing resources", "assigning assets", "managing capacity"],
    "strategic roadmap": ["long-term plan", "guiding document", "vision outline"],
    "milestone-driven": ["goal-oriented", "results-focused", "achievement-based"],
    "outcome-oriented": ["results-focused", "goal-oriented", "performance-based"],
    "deliverables": ["outputs", "results", "products"],
    "performance metrics": ["key performance indicators", "success measures", "goals"],
    "kpi framework": ["system for measuring success", "goal-setting structure", "performance evaluation model"],
    "opportunity assessment": ["evaluating potential", "analyzing possibilities", "identifying chances"],
    "operational excellence": ["superior performance", "high efficiency", "best-in-class operations"],
    "best-in-class performance": ["top-tier results", "leading outcomes", "premier achievements"],
    "business continuity": ["disaster recovery planning", "operational resilience", "maintaining essential functions"],
    "service excellence": ["outstanding customer service", "superior support", "high-quality assistance"],
    "innovation pipeline": ["flow of new ideas", "system for developing innovations", "creativity process"],
    "scalable model": ["expandable system", "flexible architecture", "growth-ready platform"],
    "elasticity": ["flexibility", "adaptability", "responsiveness"],
    "platform-agnostic": ["works on any system", "cross-platform compatible", "universal"],
    "e2e (end-to-end)": ["complete", "full", "comprehensive"],
    "best-fit solution": ["most suitable option", "optimal choice", "ideal answer"],
    "long-term vision": ["future plan", "strategic outlook", "forward-looking perspective"],
    "short-term wins": ["quick successes", "immediate achievements", "early victories"],
    "value proposition": ["unique selling point", "key benefit", "customer advantage"],
    "total cost of ownership": ["full cost over time", "lifecycle cost", "long-term expense"],
    "return on investment": ["profitability", "gains from investment", "financial return"],
    "roi": ["return on investment", "profitability", "gains from investment"],
    "sla (service level agreement)": ["service contract", "performance guarantee", "uptime promise"],
    "uptime guarantee": ["availability promise", "reliability pledge", "service level agreement"],
    "continuous learning": ["ongoing education", "lifelong learning", "constant skill development"],
    "adaptive": ["flexible", "responsive", "adjustable"],
    "responsive": ["adaptive", "flexible", "quick to react"],
    "collaborative framework": ["teamwork structure", "joint effort model", "cooperative system"],
    "business agility": ["ability to adapt quickly", "organizational flexibility", "nimbleness"],
    "cloud migration": ["moving to the cloud", "cloud adoption", "data center transition"],
    "data migration": ["moving data", "data transfer", "information relocation"],
    "digital enablement": ["empowering with technology", "facilitating digital adoption", "supporting tech use"],
    "capacity planning": ["resource management", "workload forecasting", "future needs assessment"],
    "resilience": ["durability", "robustness", "ability to recover"],
    "redundancy": ["backup systems", "failover protection", "duplication for safety"],
    "single pane of glass": ["unified view", "centralized dashboard", "integrated interface"],
    "governance": ["oversight", "management", "control"],
    "custodianship": ["stewardship", "responsibility", "care"],
    "compliance audit": ["regulatory review", "standards check", "policy inspection"],
    "risk assessment": ["threat analysis", "vulnerability evaluation", "danger identification"],
    "stakeholder alignment": ["getting everyone on the same page", "unifying interested parties", "building consensus"],
    "championing change": ["advocating for new ideas", "promoting innovation", "leading transformation"],
    "optimization roadmap": ["plan for improvement", "strategy for enhancement", "guide to refinement"],
    "portfolio management": ["managing a collection of projects", "overseeing investments", "balancing initiatives"],
    "legacy modernization": ["updating old systems", "revamping outdated technology", "bringing systems up-to-date"],
    "technical debt": ["future cost of rework", "implied cost of shortcuts", "long-term consequences of poor design"],
    "scalability testing": ["performance testing under load", "evaluating growth capacity", "stress testing"],
    "solution stack": ["set of technologies used", "technology toolkit", "software and hardware combination"],
    "technology stack": ["set of technologies used", "solution stack", "software and hardware combination"],
    "stack agnostic": ["works with any technology", "platform-independent", "universal"],
    "technology partner": ["collaborator on tech projects", "ally in development", "joint venture for innovation"],
    "innovation strategy": ["plan for creating new things", "approach to invention", "roadmap for development"],
    "competitive advantage": ["what makes you better than others", "unique selling proposition", "market edge"],
    "ai-first": ["prioritizing artificial intelligence", "focusing on AI", "leading with AI"],
}

AI_TELL_SUGGESTIONS = {
    "as an ai language model, i…": ["As a language model,", "As a large language model,", "I am a large language model, and"],
    "as requested, here is…": ["Here is", "Here is the information you requested:", "Here is what you asked for:"],
    "certainly! here’s a…": ["Certainly, here is", "Of course, here is", "Here is"],
    "i hope this helps.": ["I hope this is helpful.", "I hope this is useful.", "I hope this answers your question."],
    "please let me know if you need anything else.": ["Let me know if you need anything else.", "Feel free to ask if you need anything else.", "I'm here if you need anything else."],
    "if you have any other questions, feel free to ask.": ["Feel free to ask any other questions.", "I'm here if you have any other questions.", "Let me know if you have any other questions."],
    "i’m happy to assist you with…": ["I can help you with", "I can assist you with", "I can help with"],
    "based on your input, here is…": ["Based on your input,", "Here is what I found based on your input:", "Here is a response to your input:"],
    "to answer your question, …": ["To answer you,", "In response to your question,", "The answer is"],
    "it’s important to note that…": ["Note that", "Keep in mind", "Remember that"],
    "in conclusion,": ["To conclude,", "In summary,", "To sum up,"],
    "in summary,": ["In short,", "To summarize,", "Briefly,"],
    "here’s a breakdown…": ["Here is a breakdown:", "The steps are:", "Here is the process:"],
    "here are some suggestions…": ["Here are some ideas:", "Here are some recommendations:", "Here are some thoughts:"],
    "this can be achieved by…": ["This can be done by", "You can do this by", "This is possible by"],
    "as shown above/below,": ["As shown above,", "As shown below,", "As you can see,"],
    "let’s explore this further…": ["Let's explore this more,", "Let's look at this further,", "Let's examine this further,"],
    "here is an example:": ["For example:", "For instance:", "As an example:"],
    "here are a few key points to consider:": ["Consider these points:", "Keep these points in mind:", "Here are some important points:"],
    "please note:": ["Note:", "Keep in mind:", "Remember:"],
    "you may also want to consider…": ["You might also consider", "You could also consider", "Another option is"],
    "if you’d like more information, let me know.": ["Let me know if you want more information.", "I can provide more information if you'd like.", "I'm here if you want more information."],
    "the following are…": ["Here are", "The following is", "Below are"],
    "it’s worth mentioning that…": ["It's worth noting that", "It's important to note that", "Note that"],
    "keep in mind that…": ["Remember that", "Note that", "It's important to remember that"],
    "for your convenience, here’s…": ["For your convenience,", "Here is", "Here are"],
    "in this response, i will…": ["In this response,", "I will", "I'll"],
    "it is important to understand that…": ["It's important to understand that", "It's important to know that", "You should know that"],
    "let’s take a closer look at…": ["Let's examine", "Let's analyze", "Let's investigate"],
    "with that said,": ["However,", "Nevertheless,", "Nonetheless,"],
    "to provide more detail,": ["To provide more details,", "In more detail,", "To be more specific,"],
    "to summarize,": ["In short,", "To sum up,", "Briefly,"],
    "here’s what you need to know:": ["Here is what you need to know:", "This is what you need to know:", "Here are the key points:"],
    "that being said,": ["However,", "Nevertheless,", "Nonetheless,"],
    "to elaborate further,": ["To elaborate,", "To explain further,", "In more detail,"],
    "below is…": ["Here is", "The following is", "Below are"],
    "let’s break it down:": ["Here is a breakdown:", "The steps are:", "Here is the process:"],
    "for example,": ["For instance,", "To illustrate,", "As an example,"],
    "to get started,": ["To begin,", "To start,", "First,"],
    "as a helpful assistant,": ["As an assistant,", "As a tool,", "As a resource,"],
    "i can provide you with…": ["I can provide you with", "I can give you", "I can offer you"],
    "in other words,": ["To put it another way,", "In simpler terms,", "That is to say,"],
    "this is because…": ["This is due to", "The reason is", "This is a result of"],
    "here’s how you can…": ["Here's how to", "You can do this by", "This is how to"],
    "this process involves…": ["This involves", "The process is", "The steps are"],
    "by following these steps,": ["Follow these steps:", "By doing this,", "This will"],
    "let’s dive in,": ["Let's begin,", "Let's start,", "Let's get started,"],
    "let me know if you need additional clarification.": ["Let me know if you need more clarification.", "Feel free to ask for more clarification.", "I'm here if you need more clarification."],
    "overuse of em dashes (“—”)": ["use sparingly", "avoid excessive use", "consider alternatives"],
    "excessively correct oxford commas": ["use naturally", "don't force it", "vary sentence structure"],
    "double spaces after periods": ["use a single space", "modern standard", "web-friendly"],
    "overly neat bulleted/numbered lists": ["vary formatting", "use paragraphs", "break up lists"],
    "markdown formatting": ["use rich text", "avoid raw markdown", "format for readability"],
    "quoting or italicizing inline": ["use for emphasis only", "avoid overusing", "integrate smoothly"],
    "as mentioned earlier,": ["as noted before", "as previously stated", "earlier, I said"],
    "as previously discussed,": ["as we covered", "as mentioned before", "in our last discussion"],
    "according to your request,": ["as you asked", "per your request", "here is what you wanted"],
    "let’s proceed as follows,": ["here is the plan", "the next steps are", "this is how we'll continue"],
    "i will now…": ["next, I will", "I'm going to", "the next step is to"],
    "let’s address your question in detail:": ["let's look at your question closely", "here is a detailed answer", "examining your question"],
    "now, let’s move on to…": ["next", "moving on", "the next topic is"],
    "as outlined above,": ["as described earlier", "as previously mentioned", "following the outline"],
    "below are…": ["here are", "the following are", "you can see below"],
    "the steps are as follows:": ["here are the steps", "follow these steps", "the process is"],
    "please note that i am an ai developed by": ["I am a large language model", "I am an AI assistant", "I am a conversational AI"],
    "always consult a qualified professional": ["seek expert advice", "talk to a professional", "get a second opinion"],
    "this information is for educational purposes only": ["for learning purposes only", "not professional advice", "for informational use"],
    "i am not a lawyer, but…": ["while I'm not a legal expert", "this is not legal advice", "consult a lawyer for"],
    "i am not a medical professional, so…": ["this is not medical advice", "consult a doctor for", "for health questions, ask a professional"],
    "make sure to double-check…": ["verify", "confirm", "check again"],
    "remember, this is just an example…": ["this is an illustration", "for example", "this is a sample"],
    "step 1, step 2, step 3": ["first, second, third", "in sequence", "follow these steps"],
    "unusually balanced sections/paragraphs": ["vary paragraph length", "use different structures", "avoid uniformity"],
    "segue phrases at the start/end of each section": ["use natural transitions", "avoid formulaic phrases", "connect ideas smoothly"],
    "additionally,": ["also", "in addition", "furthermore"],
    "moreover,": ["also", "in addition", "furthermore"],
    "furthermore,": ["also", "in addition", "moreover"],
    "consequently,": ["as a result", "therefore", "so"],
    "in contrast,": ["however", "on the other hand", "conversely"],
    "however,": ["but", "yet", "still"],
    "overly formal tone": ["use a more natural voice", "be less stiff", "write conversationally"],
    "over-explaining simple things": ["be concise", "keep it simple", "avoid unnecessary detail"],
    "significantly": ["importantly", "notably", "considerably"],
    "effectively": ["successfully", "productively", "efficiently"],
    "efficiently": ["productively", "effectively", "without waste"],
    "particularly": ["especially", "specifically", "in particular"],
    "primarily": ["mainly", "mostly", "chiefly"],
    "essentially": ["basically", "fundamentally", "in essence"],
    "subsequently": ["later", "afterward", "then"],
    "comprehensive": ["complete", "thorough", "full"],
    "holistic": ["comprehensive", "complete", "integrated"],
    "detailed": ["thorough", "in-depth", "specific"],
    "thorough": ["detailed", "in-depth", "complete"],
    "exhaustive": ["comprehensive", "complete", "thorough"],
    "pivotal": ["crucial", "critical", "key"],
    "critical": ["crucial", "vital", "essential"],
    "integral": ["essential", "fundamental", "key"],
    "seamlessly": ["smoothly", "effortlessly", "without interruption"],
    "robustly": ["strongly", "solidly", "reliably"],
    "intuitively": ["instinctively", "naturally", "easily"],
    "dynamically": ["actively", "energetically", "changingly"],
    "proactively": ["taking initiative", "acting in advance", "being prepared"],
    "i hope this provides clarity.": ["I hope this is clear", "I hope this explains it", "I hope this helps you understand"],
    "let me know if you have any further questions.": ["feel free to ask more questions", "I'm here for more questions", "let me know if you need more help"],
    "please let me know if you need more information.": ["ask if you need more details", "I can provide more information", "let me know if you want to know more"],
    "thank you for your question!": ["thanks for asking", "good question", "that's a great question"],
    "if you need anything else, feel free to ask.": ["I'm here if you need more help", "let me know if there's anything else", "feel free to ask for more"],
    "looking forward to assisting you further.": ["I'm ready to help more", "I look forward to helping you again", "happy to assist further"],
    "wishing you the best with your project.": ["good luck with your project", "all the best with your work", "I hope your project goes well"],
    "rare use of contractions": ["use contractions like don't, can't, it's", "write more naturally", "sound less formal"],
    "direct restatement of user’s question": ["avoid repeating the question", "get straight to the answer", "be direct"],
    "overuse of passive voice": ["use active voice", "make writing more direct", "be clear and concise"],
    "uniform sentence length": ["vary your sentence length", "use a mix of short and long sentences", "create a better rhythm"],
    "in-code comments that read like documentation": ["write concise comments", "focus on the why, not the what", "keep comments brief"],
    "use of the phrase “for example,” with a colon": ["use 'for example' or 'e.g.'", "integrate examples smoothly", "avoid clunky phrasing"],
    "foundation model": ["base model", "core model", "fundamental model"],
    "multimodal": ["multiple data types", "text, image, and audio", "mixed media"],
    "token efficiency/token window": ["input length", "processing limit", "model capacity"],
    "retrieval-augmented generation (rag)": ["knowledge retrieval", "external data integration", "fact-based generation"],
    "prompt engineering": ["instruction design", "query optimization", "crafting effective prompts"],
    "few-shot/zero-shot learning": ["learning from limited data", "adapting to new tasks", "sample-efficient learning"],
    "model alignment": ["behavior tuning", "value alignment", "ethical fine-tuning"],
    "guardrails": ["safety filters", "content restrictions", "ethical boundaries"],
    "hallucination/hallucinate": ["factual error", "made-up information", "generated falsehood"],
    "system prompt/user prompt": ["initial instruction", "user query", "input text"],
    "chain-of-thought (cot)": ["step-by-step reasoning", "logical process", "thought process"],
    "instruction tuning": ["task-specific training", "fine-tuning with instructions", "behavioral adaptation"],
    "context window": ["input size limit", "token capacity", "memory length"],
    "fine-tuning/fine-tuned": ["specialized training", "domain adaptation", "model customization"],
    "temperature/top-k/top-p sampling": ["randomness control", "creativity vs. coherence", "output diversity"],
    "model weights": ["internal parameters", "learned knowledge", "neural network data"],
    "open weights/closed weights": ["public vs. private models", "accessible vs. proprietary", "shared vs. secret"],
    "model quantization/lora adapters": ["model compression", "efficient fine-tuning", "performance optimization"],
    "inference latency": ["response time", "processing speed", "generation delay"],
    "output token limit": ["max response length", "generation cutoff", "output size"],
    "llmops": ["managing large language models", "AI model lifecycle", "operationalizing LLMs"],
    "prompt injection/prompt leakage": ["security vulnerability", "malicious input", "data extraction"],
    "red-teaming": ["adversarial testing", "security audit", "finding weaknesses"],
    "synthetic data": ["artificially generated data", "simulated information", "fake data"],
    "safety review": ["ethical assessment", "risk analysis", "security check"],
    "fact-checking pipeline": ["verification process", "accuracy validation", "information checking"],
    "output filtering": ["content moderation", "response cleaning", "result filtering"],
    "safety system": ["protection mechanism", "security layer", "risk mitigation"],
    "explainability/interpretable ai": ["transparency", "understanding model decisions", "black box vs. white box"],
    "self-consistency": ["reliable outputs", "consistent reasoning", "stable results"],
    "token gating": ["access control", "usage limits", "permission management"],
    "voice cloning": ["synthetic voice generation", "voice replication", "AI voice mimicry"],
    "responsible ai": ["ethical AI", "trustworthy AI", "accountable AI"],
    "model distillation": ["knowledge transfer", "model compression", "creating smaller models"],
    "here’s a quick summary:": ["in short", "to sum up", "in brief"],
    "you can find more details at [link]": ["for more information, see [link]", "read more at [link]", "details are at [link]"],
    "let me walk you through…": ["let me explain", "here is a step-by-step guide", "I'll show you how"],
    "here’s what i found for you:": ["here is what I found", "I found this information", "this is what I discovered"],
    "certainly, here’s a list:": ["here is a list", "of course, here are the items", "here are the things you asked for"],
    "if you’d like to continue, just ask!": ["ask to continue", "let me know if you want more", "I can provide more information"],
    "let’s break this down:": ["let's analyze this", "here is a breakdown", "let's look at the parts"],
    "here are some steps you can follow:": ["follow these steps", "here is the process", "you can do this by"],
    "to get started,": ["to begin", "first", "to start"],
    "if you’d like me to elaborate…": ["I can explain further", "let me know if you want more detail", "I can provide more information"],
    "(just to clarify)": ["to be clear", "for clarification", "in other words"],
    "deep dive": ["in-depth analysis", "thorough examination", "detailed look"],
    "delve": ["explore", "investigate", "examine"],
    "unpack": ["analyze", "explain", "break down"],
    "let’s explore": ["let's look at", "let's examine", "let's investigate"],
    "remember that ai models are not perfect…": ["AI models have limitations", "AI is not always accurate", "be aware of AI errors"],
    "this function does x": ["this function performs X action", "the purpose of this function is", "this code does X"],
    "perfectly formatted code blocks": ["format code for readability", "use consistent styling", "make code easy to read"],
    "excessively complete error-handling in examples": ["show realistic error handling", "don't overdo it", "focus on the main logic"],
    'print("hello, world!")': ["use a more descriptive example", "show a relevant use case", "avoid generic examples"],
    "explaining every variable and parameter": ["be concise", "focus on important details", "don't over-explain"],
    "for example, a restaurant may want to…": ["for instance, a business might", "as an example, a company could", "imagine a scenario where"],
    "imagine you’re building an app that…": ["if you were creating an app that", "for an application that", "in a software development context"],
    "suppose you have a dataset with…": ["if you have data that", "with a dataset containing", "for a data analysis task"],
    "teaching a student": ["educating someone", "explaining to a learner", "instructing a novice"],
    "training a dog": ["house-training a pet", "teaching a command", "animal training"],
    "learning a language": ["studying a new language", "language acquisition", "becoming bilingual"],
    "here are some next steps you can take:": ["here's what to do next", "your next steps are", "what to do now"],
    "consider the following options:": ["here are some choices", "you could", "think about these options"],
    "to further enhance your workflow, you might want to…": ["to improve your process, you could", "to make things even better, try", "to boost your efficiency, consider"],
}

CLICHE_SUGGESTIONS = {
    "it’s important to note that…": ["Note that", "Keep in mind", "Remember that"],
    "in conclusion,": ["To conclude,", "In summary,", "To sum up,"],
    "in summary,": ["In short,", "To summarize,", "Briefly,"],
    "to summarize,": ["In short,", "To sum up,", "Briefly,"],
    "here’s a breakdown…": ["Here is a breakdown:", "The steps are:", "Here is the process:"],
    "for example,": ["For instance,", "To illustrate,", "As an example,"],
    "to illustrate,": ["For example,", "For instance,", "As an illustration,"],
    "let’s break it down:": ["Here is a breakdown:", "The steps are:", "Here is the process:"],
    "let’s take a closer look at…": ["Let's examine", "Let's analyze", "Let's investigate"],
    "let’s dive in,": ["Let's begin,", "Let's start,", "Let's get started,"],
    "here are some key points to consider:": ["Consider these points:", "Keep these points in mind:", "Here are some important points:"],
    "that being said,": ["However,", "Nevertheless,", "Nonetheless,"],
    "with that said,": ["However,", "Nevertheless,", "Nonetheless,"],
    "this can be achieved by…": ["This can be done by", "You can do this by", "This is possible by"],
    "to get started,": ["To begin,", "To start,", "First,"],
    "by following these steps,": ["Follow these steps:", "By doing this,", "This will"],
    "here’s how you can…": ["Here's how to", "You can do this by", "This is how to"],
    "this process involves…": ["This involves", "The process is", "The steps are"],
    "here’s an example:": ["For example:", "For instance:", "As an example:"],
    "now, let’s move on to…": ["Next,", "Now, let's discuss", "Let's turn to"],
    "as mentioned earlier,": ["As stated before,", "As previously mentioned,", "As noted earlier,"],
    "as previously discussed,": ["As discussed before,", "As previously mentioned,", "As noted earlier,"],
    "according to your request,": ["As you requested,", "As requested,", "Here is what you asked for:"],
    "to answer your question,": ["To answer you,", "In response to your question,", "The answer is"],
    "i hope this helps.": ["I hope this is helpful.", "I hope this is useful.", "I hope this answers your question."],
    "please let me know if you have any further questions.": ["Let me know if you have more questions.", "Feel free to ask more questions.", "I'm here if you have more questions."],
    "if you have any other questions, feel free to ask.": ["Feel free to ask more questions.", "I'm here if you have more questions.", "Let me know if you have more questions."],
    "based on your input, here is…": ["Based on your input,", "Here is what I found based on your input:", "Here is a response to your input:"],
    "if you’d like more information, let me know.": ["Let me know if you want more information.", "I can provide more information if you'd like.", "I'm here if you want more information."],
    "you may also want to consider…": ["You might also consider", "You could also consider", "Another option is"],
    "keep in mind that…": ["Remember that", "Note that", "It's important to remember that"],
    "the following are…": ["Here are", "The following is", "Below are"],
    "below is…": ["Here is", "The following is", "Below are"],
    "here’s what you need to know:": ["Here is what you need to know:", "This is what you need to know:", "Here are the key points:"],
    "to elaborate further,": ["To elaborate,", "To explain further,", "In more detail,"],
    "in other words,": ["To put it another way,", "In simpler terms,", "That is to say,"],
    "this is because…": ["This is due to", "The reason is", "This is a result of"],
    "here’s what i found for you:": ["Here is what I found:", "I found this for you:", "Here is the information you requested:"],
    "it’s worth mentioning that…": ["It's worth noting that", "It's important to note that", "Note that"],
    "let me walk you through…": ["Let me explain", "Let me show you", "Let me guide you through"],
    "here’s a quick summary:": ["Here is a quick summary:", "In short:", "To summarize:"],
    "let’s explore this further…": ["Let's explore this more,", "Let's look at this further,", "Let's examine this further,"],
    "as outlined above,": ["As stated above,", "As mentioned above,", "As noted above,"],
    "here’s how to approach this:": ["Here is how to approach this:", "This is how to approach this:", "Here are the steps to approach this:"],
    "a common approach is to…": ["A common way is to", "A common method is to", "A common strategy is to"],
    "a great way to…": ["A good way to", "A great method is to", "A great strategy is to"],
    "a key takeaway is…": ["The key takeaway is", "The main point is", "The most important thing is"],
    "the main objective is to…": ["The main goal is to", "The main purpose is to", "The main aim is to"],
    "one thing to consider is…": ["One thing to think about is", "One thing to keep in mind is", "One thing to remember is"],
    "another important aspect is…": ["Another important point is", "Another important thing is", "Another important consideration is"],
    "a useful strategy is…": ["A useful method is", "A useful approach is", "A useful way is"],
    "on the other hand,": ["However,", "Conversely,", "In contrast,"],
    "conversely,": ["However,", "On the other hand,", "In contrast,"],
    "in contrast,": ["However,", "On the other hand,", "Conversely,"],
    "additionally,": ["Also,", "In addition,", "Furthermore,"],
    "moreover,": ["Also,", "In addition,", "Furthermore,"],
    "furthermore,": ["Also,", "In addition,", "Moreover,"],
    "consequently,": ["As a result,", "Therefore,", "Because of this,"],
    "however,": ["But,", "Nevertheless,", "Nonetheless,"],
    "therefore,": ["As a result,", "Consequently,", "Because of this,"],
    "overall,": ["In general,", "All in all,", "In conclusion,"],
    "ultimately,": ["In the end,", "Finally,", "In conclusion,"],
    "remember,": ["Keep in mind,", "Note that,", "It's important to remember that"],
    "always consult a qualified professional…": ["Consult a professional", "Get professional advice", "Talk to an expert"],
    "this information is for educational purposes only…": ["This is for educational purposes only", "This is for informational purposes only", "This is not professional advice"],
    "make sure to double-check…": ["Double-check", "Verify", "Confirm"],
    "it’s always a good idea to…": ["It's a good idea to", "You should", "It's best to"],
    "imagine you’re building…": ["Imagine you are building", "Suppose you are building", "If you were building"],
    "suppose you have…": ["Suppose you have", "Imagine you have", "If you have"],
    "whether you’re a beginner or an expert,": ["Whether you are a beginner or an expert,", "Regardless of your experience level,", "No matter your background,"],
    "regardless of experience level,": ["Regardless of your experience,", "No matter your experience,", "Whether you are a beginner or an expert,"],
    "no matter your background,": ["No matter your experience,", "Regardless of your background,", "Whether you are a beginner or an expert,"],
    "a good rule of thumb is…": ["A good rule is", "A good guideline is", "A good principle is"],
    "as a helpful assistant,": ["As an assistant,", "As a tool,", "As a resource,"],
    "in the world of…": ["In the field of", "In the area of", "In"],
    "in today’s fast-paced environment,": ["In today's environment,", "In the current environment,", "Today,"],
    "in today’s digital age,": ["In the digital age,", "In the current age,", "Today,"],
    "in a nutshell,": ["In short,", "Briefly,", "To summarize,"],
    "at the end of the day,": ["Ultimately,", "In the end,", "In conclusion,"],
    "the bottom line is…": ["The main point is", "The most important thing is", "The key takeaway is"],
    "the best of both worlds,": ["The best of both", "A win-win", "A perfect combination"],
    "take it to the next level,": ["Improve it", "Enhance it", "Make it better"],
    "level up your [x],": ["Improve your [X]", "Enhance your [X]", "Make your [X] better"],
    "unlock your potential,": ["Realize your potential", "Achieve your potential", "Reach your potential"],
    "harness the power of…": ["Use the power of", "Take advantage of the power of", "Utilize the power of"],
    "the sky’s the limit,": ["Anything is possible", "There are no limits", "The possibilities are endless"],
    "think outside the box,": ["Be creative", "Be innovative", "Think differently"],
    "stay ahead of the curve,": ["Stay ahead of the competition", "Be a leader", "Be a trendsetter"],
    "all things considered,": ["Overall,", "In conclusion,", "In summary,"],
    "from start to finish,": ["From beginning to end", "Completely", "Throughout"],
}

with open("jargon_suggestions.py", "w") as f:
    f.write(f"JARGON_SUGGESTIONS = {JARGON_SUGGESTIONS}")

with open("ai_tell_suggestions.py", "w") as f:
    f.write(f"AI_TELL_SUGGESTIONS = {AI_TELL_SUGGESTIONS}")

with open("cliche_suggestions.py", "w") as f:
    f.write(f"CLICHE_SUGGESTIONS = {CLICHE_SUGGESTIONS}")
